# Generated by Django 3.2.16 on 2023-01-06 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('subname', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_info', models.TextField(blank=True, null=True)),
                ('avatar', models.ImageField(default='../default_profile_opkx3m', upload_to='images/')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('status', models.CharField(blank=True, choices=[('BM', 'Looking for bandmembers'), ('LB', 'Looking for band')], max_length=2, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
