# Generated by Django 3.2.16 on 2023-06-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, choices=[('BM', 'Looking for bandmembers'), ('LB', 'Looking for band'), ('AS', 'All set!')], max_length=2, null=True),
        ),
    ]
