# Generated by Django 3.2.16 on 2023-01-13 14:11

import cloudinary_storage.storage
from django.db import migrations, models
import song.validators


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0004_alter_song_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio',
            field=models.ImageField(default='songs/rock_it_pycp3h', storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='songs/', validators=[song.validators.validate_audio]),
        ),
    ]
