# Generated by Django 3.2.16 on 2023-01-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio',
            field=models.FileField(default='songs/rock_it_pycp3h', upload_to='songs/'),
        ),
    ]
