# Generated by Django 3.2.16 on 2023-01-11 15:38

import cloudinary_storage.storage
import cloudinary_storage.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_alter_song_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio',
            field=models.FileField(default='songs/rock_it_pycp3h', storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='songs/', validators=[cloudinary_storage.validators.validate_video]),
        ),
    ]
